/*
  ==============================================================================

	This file was auto-generated by the Introjucer!

	It contains the basic startup code for a Juce application.
	Created: xx.xx.2014

  ==============================================================================
*/

#include "Main.h"

#include "MainWindow.h"
#include "MainComponent.h"

#include "FirmwareTransfer.h"

#include "LumatoneEditorLookAndFeel.h"

#include "./lumatone_editor_library/device/lumatone_controller.h"
#include "./lumatone_editor_library/device/activity_monitor.h"
#include "./lumatone_editor_library/graphics/view_constants.h"
#include "./lumatone_editor_library/palettes/colour_palette_file.h"

#include "GeneralOptionsDlg.h"
#include "VelocityCurveDlgBase.h"
#include "NoteOnOffVelocityCurveDialog.h"
#include "LumatoneMenu.h"

//==============================================================================

MainContentComponent* TerpstraSysExApplication::getMainContentComponent() const
{
	jassert(mainWindow != nullptr);
	return (MainContentComponent*)(mainWindow->getContentComponent());
}

TerpstraSysExApplication::TerpstraSysExApplication()
	: firmwareDriver(LumatoneFirmwareDriver::HostMode::Driver)
	, state("LumatoneEditor", firmwareDriver, &undoManager)
{
	activityMonitor.reset(new DeviceActivityMonitor(&firmwareDriver, state));

	// Localisation
	String localisation = getLocalisation(SystemStats::getDisplayLanguage());
	LocalisedStrings::setCurrentMappings(new LocalisedStrings(localisation, false));
	LocalisedStrings::getCurrentMappings()->setFallback(new LocalisedStrings(BinaryData::engb_txt, false));

	 reloadColourPalettes();
}
//
//LumatoneFirmwareDriver& TerpstraSysExApplication::initializeDriver()
//{
//	firmwareDriver = new LumatoneFirmwareDriver(LumatoneFirmwareDriver::HostMode::Driver);
//	return *firmwareDriver;
//}

//==============================================================================
void TerpstraSysExApplication::initialise(const String& commandLine)
{
	// This method is where you should put your application's initialisation code..

	// commandLine parameters
	if (!commandLine.isEmpty())
	{
		auto commandLineParameters = getCommandLineParameterArray();

		for (auto commandLineParameter : commandLineParameters)
		{
			// ToDo switch on/off isomorphic mass assign mode

			// Try to open a config file
			if (File::isAbsolutePath(commandLineParameter))
			{
				state.currentFile = File(commandLineParameter);
			}
			else
			{
				// If file name is with quotes, try removing the quotes
				if (commandLine.startsWithChar('"') && commandLine.endsWithChar('"'))
					state.currentFile = File(commandLine.substring(1, commandLine.length() - 1));
					//state.setCurrentFile(commandLine.substring(1, commandLine.length()-1));
			}

			if (state.getCurrentFile().existsAsFile())
				break;	// There can only be one file, and the file name is supposed to be the last parameter
		}
	}

	commandManager.reset(new ApplicationCommandManager());
	commandManager->registerAllCommandsForTarget(this);

	boundsConstrainer = std::make_unique<ComponentBoundsConstrainer>();

	mainWindow.reset(new MainWindow(state, commandManager.get()));
	mainWindow->restoreStateFromPropertiesFile(state.propertiesFile.get());


	if (state.getCurrentFile().existsAsFile())
		state.openFromCurrentFile();
}

void TerpstraSysExApplication::shutdown()
{
	// Add your application's shutdown code here..

	// Save documents directories (Future: provide option to change them and save after changed by user)
	state.propertiesFile->setValue("UserDocumentsDirectory", state.getUserDocumentsDirectory().getFullPathName());
	state.propertiesFile->setValue("UserMappingsDirectory", state.getUserMappingsDirectory().getFullPathName());
	state.propertiesFile->setValue("UserPalettesDirectory", state.getUserPalettesDirectory().getFullPathName());

	// Save recent files list
	state.recentFiles.removeNonExistentFiles();
	jassert(state.propertiesFile != nullptr);
	state.propertiesFile->setValue("RecentFiles", state.recentFiles.toString());

	// Save state of main window
	mainWindow->saveStateToPropertiesFile(state.propertiesFile.get());

	state.propertiesFile->saveIfNeeded();
	state.propertiesFile = nullptr;

	LocalisedStrings::setCurrentMappings(nullptr);

    mainWindow = nullptr;

	if (state.firmwareUpdateCompleted())
		FirmwareTransfer::exitLibSsh2();

	activityMonitor = nullptr;
	//delete firmwareDriver;

//	commandManager = nullptr;
}

//==============================================================================
void TerpstraSysExApplication::systemRequestedQuit()
{
	// This is called when the app is being asked to quit: you can ignore this
	// request and let the app carry on running, or call quit() to allow the app to close.

	// If there are changes: ask for save
	if (state.getHasChangesToSave())
	{
		AlertWindow::showYesNoCancelBox(
			AlertWindow::AlertIconType::QuestionIcon,
			"Quitting the application",
			"Do you want to save your changes?",
			"Yes", "No", "Cancel", nullptr,
			ModalCallbackFunction::create([&](int retc)
			{
				if (retc == 0)
				{
					// "Cancel". Do not quit.
					return;
				}
				else if (retc == 1)
				{
					// "Yes". Try to save. Cancel if unsuccessful
					saveSysExMapping([&](bool success) { if (success) quit(); });
				}
				else
				{
					// retc == 2: "No" -> end without saving
					quit();
				}
			})
		);

		return;
	}

	quit();
}

void TerpstraSysExApplication::anotherInstanceStarted(const String& commandLine)
{
	// When another instance of the app is launched while this one is running,
	// this method is invoked, and the commandLine parameter tells you what
	// the other instance's command-line arguments were.
}

bool TerpstraSysExApplication::saveColourPalette(LumatoneEditorColourPalette& palette, File pathToFile)
{
	bool success = false;

	if (palette.hasBeenModified())
	{
		ValueTree paletteNode = palette.toValueTree();

		if (pathToFile == File())
			pathToFile = File(palette.getPathToFile());

        // If name changed, delete the old one
        if (pathToFile.exists())
        {
            auto currentName = pathToFile.getFileName();
            if (currentName != palette.getName())
            {
                pathToFile.deleteFile();
            }
        }

		// New file
		if (!pathToFile.existsAsFile())
		{
            String fileName = "UnnamedPalette";

			if (palette.getName().isNotEmpty())
                fileName = palette.getName();

            pathToFile = state.getUserPalettesDirectory().getChildFile(fileName);

			// Make sure filename is unique since saving happens automatically
            // Sorry programmers, we're using cardinal numbers here, and the original is implicitly #1 ;)
			int nameId = 1;
			while (pathToFile.withFileExtension(PALETTEFILEEXTENSION).existsAsFile() && nameId < 999999)
			{
                auto fileNameToSave = fileName + "_" + String(++nameId);
                pathToFile = state.getUserPalettesDirectory().getChildFile(fileNameToSave);
			}
		}

		success = palette.saveToFile(pathToFile);

		// TODO error handling?
	}

	// if (success)
		// reloadColourPalettes();

	return success;
}

void TerpstraSysExApplication::reloadColourPalettes()
{
    auto directory = state.getUserPalettesDirectory();
	auto foundPaletteFiles = directory.findChildFiles(juce::File::TypesOfFileToFind::findFiles, true, '*' + juce::String(PALETTEFILEEXTENSION));

	juce::Array<LumatoneEditorColourPalette> newPalettes;

	auto paletteSorter = LumatoneEditorPaletteSorter();
	for (auto file : foundPaletteFiles)
	{
		LumatoneEditorColourPalette palette = LumatoneEditorColourPalette::loadFromFile(file);
		newPalettes.addSorted(paletteSorter, palette);
	}

	state.setColourPalettes(newPalettes);
}

void TerpstraSysExApplication::getAllCommands(Array <CommandID>& commands)
{
	JUCEApplication::getAllCommands(commands);

	const CommandID ids[] = {
		Lumatone::Menu::commandIDs::openSysExMapping,
		Lumatone::Menu::commandIDs::saveSysExMapping,
		Lumatone::Menu::commandIDs::saveSysExMappingAs,
		Lumatone::Menu::commandIDs::resetSysExMapping,

		Lumatone::Menu::commandIDs::deleteOctaveBoard,
		Lumatone::Menu::commandIDs::copyOctaveBoard,
		Lumatone::Menu::commandIDs::pasteOctaveBoard,
        Lumatone::Menu::commandIDs::pasteOctaveBoardChannels,
        Lumatone::Menu::commandIDs::pasteOctaveBoardNotes,
        Lumatone::Menu::commandIDs::pasteOctaveBoardColours,
        Lumatone::Menu::commandIDs::pasteOctaveBoardTypes,

		Lumatone::Menu::commandIDs::undo,
		Lumatone::Menu::commandIDs::redo,

		Lumatone::Debug::commandIDs::toggleDeveloperMode,

		Lumatone::Menu::commandIDs::aboutSysEx
	};

	commands.addArray(ids, numElementsInArray(ids));
}

void TerpstraSysExApplication::getCommandInfo(CommandID commandID, ApplicationCommandInfo& result)
{
	switch (commandID)
	{
	case Lumatone::Menu::commandIDs::openSysExMapping:
		result.setInfo("Load file mapping", "Open a Lumatone key mapping", "File", 0);
		result.addDefaultKeypress('o', ModifierKeys::commandModifier);
		break;

	case Lumatone::Menu::commandIDs::saveSysExMapping:
		result.setInfo("Save mapping", "Save the current mapping to file", "File", 0);
		result.addDefaultKeypress('s', ModifierKeys::commandModifier);
		break;

	case Lumatone::Menu::commandIDs::saveSysExMappingAs:
		result.setInfo("Save mapping as...", "Save the current mapping to new file", "File", 0);
		result.addDefaultKeypress('a', ModifierKeys::commandModifier);
		break;

	case Lumatone::Menu::commandIDs::resetSysExMapping:
		result.setInfo("New", "Start new mapping. Clear all edit fields, do not save current edits.", "File", 0);
		result.addDefaultKeypress('n', ModifierKeys::commandModifier);
		break;

	case Lumatone::Menu::commandIDs::deleteOctaveBoard:
		result.setInfo("Delete", "Delete section data", "Edit", 0);
		result.addDefaultKeypress(KeyPress::deleteKey, ModifierKeys::noModifiers);
		break;

	case Lumatone::Menu::commandIDs::copyOctaveBoard:
		result.setInfo("Copy section", "Copy current octave board data", "Edit", 0);
		result.addDefaultKeypress('c', ModifierKeys::commandModifier);
		break;

	case Lumatone::Menu::commandIDs::pasteOctaveBoard:
		result.setInfo("Paste section", "Paste copied section data", "Edit", 0);
		result.addDefaultKeypress('v', ModifierKeys::commandModifier);
        result.setActive(canPasteSubBoardData());
		break;

    case Lumatone::Menu::commandIDs::pasteOctaveBoardNotes:
        result.setInfo("Paste notes", "Paste copied section notes", "Edit", 0);
        result.addDefaultKeypress('v', ModifierKeys::commandModifier | ModifierKeys::shiftModifier);
        result.setActive(canPasteSubBoardData());
        break;

    case Lumatone::Menu::commandIDs::pasteOctaveBoardChannels:
        result.setInfo("Paste channels", "Paste copied section channels", "Edit", 0);
        result.addDefaultKeypress('v', ModifierKeys::commandModifier | ModifierKeys::altModifier);
        result.setActive(canPasteSubBoardData());
        break;

    case Lumatone::Menu::commandIDs::pasteOctaveBoardColours:
        result.setInfo("Paste colours", "Paste copied section colours", "Edit", 0);
        result.addDefaultKeypress('v', ModifierKeys::altModifier);
        result.setActive(canPasteSubBoardData());
        break;

    case Lumatone::Menu::commandIDs::pasteOctaveBoardTypes:
        result.setInfo("Paste types", "Paste copied section key types", "Edit", 0);
        result.addDefaultKeypress('v', ModifierKeys::altModifier | ModifierKeys::shiftModifier);
        result.setActive(canPasteSubBoardData());
        break;

	case Lumatone::Menu::commandIDs::undo:
		result.setInfo("Undo", "Undo latest edit", "Edit", 0);
		result.addDefaultKeypress('z', ModifierKeys::commandModifier);
		result.setActive(undoManager.canUndo());
		break;

	case Lumatone::Menu::commandIDs::redo:
		result.setInfo("Redo", "Redo latest edit", "Edit", 0);
		result.addDefaultKeypress('y', ModifierKeys::commandModifier);
		result.addDefaultKeypress('z', ModifierKeys::commandModifier + ModifierKeys::shiftModifier);
		result.setActive(undoManager.canRedo());
		break;

	case Lumatone::Menu::commandIDs::aboutSysEx:
		result.setInfo("About Lumatone Editor", "Shows version and copyright", "Help", 0);
		break;

	case Lumatone::Debug::commandIDs::toggleDeveloperMode:
		result.setInfo("Toggle Developer Mode", "Show/hide controls for tweaking internal parameters", "Edit", 0);
		result.addDefaultKeypress('m',
                   juce::ModifierKeys::ctrlModifier + juce::ModifierKeys::altModifier + juce::ModifierKeys::shiftModifier);
		result.setActive(true);
		break;

	default:
		JUCEApplication::getCommandInfo(commandID, result);
		break;
	}
}

bool TerpstraSysExApplication::perform(const InvocationInfo& info)
{
	switch (info.commandID)
	{
	case Lumatone::Menu::commandIDs::openSysExMapping:
		return openSysExMapping();
	case Lumatone::Menu::commandIDs::saveSysExMapping:
		return saveSysExMapping();
	case Lumatone::Menu::commandIDs::saveSysExMappingAs:
		return saveSysExMappingAs();
	case Lumatone::Menu::commandIDs::resetSysExMapping:
		return resetSysExMapping();

	case Lumatone::Menu::commandIDs::deleteOctaveBoard:
		return deleteSubBoardData();
	case Lumatone::Menu::commandIDs::copyOctaveBoard:
		return copySubBoardData();
	case Lumatone::Menu::commandIDs::pasteOctaveBoard:
		return pasteSubBoardData();
    case Lumatone::Menu::commandIDs::pasteOctaveBoardNotes:
    case Lumatone::Menu::commandIDs::pasteOctaveBoardChannels:
    case Lumatone::Menu::commandIDs::pasteOctaveBoardColours:
    case Lumatone::Menu::commandIDs::pasteOctaveBoardTypes:
        return pasteModifiedSubBoardData(info.commandID);

	case Lumatone::Menu::commandIDs::undo:
		return undo();

	case Lumatone::Menu::commandIDs::redo:
		return redo();

	case Lumatone::Menu::commandIDs::aboutSysEx:
		return aboutTerpstraSysEx();

	case Lumatone::Debug::commandIDs::toggleDeveloperMode:
		return toggleDeveloperMode();
	default:
		return JUCEApplication::perform(info);
	}
}

bool TerpstraSysExApplication::openSysExMapping()
{
	fileChooser = std::make_unique<FileChooser>("Open a Lumatone key mapping", state.recentFiles.getFile(0).getParentDirectory(), "*.ltn;*.tsx");
	fileChooser->launchAsync(FileBrowserComponent::FileChooserFlags::canSelectFiles | FileBrowserComponent::FileChooserFlags::openMode,
		[&](const FileChooser& chooser)
		{
			state.currentFile = chooser.getResult();
			state.openFromCurrentFile();
		});

	return true;
}

bool TerpstraSysExApplication::saveSysExMapping(std::function<void(bool success)> saveFileCallback)
{
	if (state.getCurrentFile().getFileName().isEmpty())
		return saveSysExMappingAs(saveFileCallback);
	else
		return saveCurrentFile(saveFileCallback);

}

bool TerpstraSysExApplication::saveSysExMappingAs(std::function<void(bool)> saveFileCallback)
{
	fileChooser = std::make_unique<FileChooser>("Lumatone Key Mapping Files", state.recentFiles.getFile(0).getParentDirectory(), "*.ltn");
	fileChooser->launchAsync(FileBrowserComponent::FileChooserFlags::saveMode | FileBrowserComponent::FileChooserFlags::warnAboutOverwriting,
		[this, saveFileCallback](const FileChooser& chooser)
		{
			state.currentFile = chooser.getResult();
			bool saved = saveCurrentFile();
			if (saved)
			{
				// Window title
				updateMainTitle();
			}

			saveFileCallback(saved);
		});

	return true;
}

bool TerpstraSysExApplication::resetSysExMapping()
{
    // Clear file
    state.setCurrentFile(juce::File());

	// Clear all edit fields
	// ((MainContentComponent*)(mainWindow->getContentComponent()))->deleteAll();

	//state.setHasChangesToSave(false);

	// Clear undoable actions
	// ToDo (?)
	// undoManager.clearUndoHistory();


	// Window title
	// updateMainTitle();

	return true;
}


// Saves the current mapping to file, specified in state.getCurrentFile().
bool TerpstraSysExApplication::saveCurrentFile(std::function<void(bool success)> saveFileCallback)
{
	if (state.getCurrentFile().existsAsFile())
		state.getCurrentFile().deleteFile();
	bool retc = state.getCurrentFile().create();
	// XXX error handling

    bool appendSuccess = true;
	StringArray stringArray = state.getMappingData()->toStringArray();
	for (int i = 0; i < stringArray.size(); i++)
		appendSuccess = appendSuccess && state.getCurrentFile().appendText(stringArray[i] + "\n");

	state.setHasChangesToSave(!appendSuccess);
    saveFileCallback(appendSuccess);

	// ToDo undo history?

	// Add file to recent files list - or put it on top of the list
	state.recentFiles.addFile(state.currentFile);

	return retc;
}

// open a file from the "recent files" menu
bool TerpstraSysExApplication::openRecentFile(int recentFileIndex)
{
	jassert(recentFileIndex >= 0 && recentFileIndex < state.recentFiles.getNumFiles());
	state.currentFile = state.recentFiles.getFile(recentFileIndex);
	return state.openFromCurrentFile();
}

bool TerpstraSysExApplication::deleteSubBoardData()
{
	return performUndoableAction(((MainContentComponent*)(mainWindow->getContentComponent()))->createDeleteCurrentSectionAction());
}

bool TerpstraSysExApplication::copySubBoardData()
{
	return ((MainContentComponent*)(mainWindow->getContentComponent()))->copyCurrentSubBoardData();
}

bool TerpstraSysExApplication::pasteSubBoardData()
{
	return performUndoableAction(((MainContentComponent*)(mainWindow->getContentComponent()))->createPasteCurrentSectionAction());
}

bool TerpstraSysExApplication::pasteModifiedSubBoardData(CommandID commandID)
{
    switch (commandID)
    {
    case Lumatone::Menu::pasteOctaveBoardNotes:
    case Lumatone::Menu::pasteOctaveBoardColours:
    case Lumatone::Menu::pasteOctaveBoardChannels:
    case Lumatone::Menu::pasteOctaveBoardTypes:
        return performUndoableAction(((MainContentComponent*)(mainWindow->getContentComponent()))->createModifiedPasteCurrentSectionAction(commandID));
    default:
        jassertfalse;
        return false;
    }
}

bool TerpstraSysExApplication::canPasteSubBoardData() const
{
    if (mainWindow != nullptr)
        return getMainContentComponent()->canPasteCopiedSubBoard();
    return false;
}

bool TerpstraSysExApplication::performUndoableAction(UndoableAction* editAction, bool newTransaction)
{
	if (editAction != nullptr)
	{
		if (newTransaction)
			undoManager.beginNewTransaction();

		if (undoManager.perform(editAction))	// UndoManager will check for nullptr and also for disposing of the object
		{
			// setHasChangesToSave(true);
			((MainContentComponent*)(mainWindow->getContentComponent()))->refreshAllFields();
			return true;
		}
	}

	return false;
}

bool TerpstraSysExApplication::undo()
{
	if (undoManager.undo())
	{
		// setHasChangesToSave(true);
		// ((MainContentComponent*)(mainWindow->getContentComponent()))->refreshAllFields();
		return true;
	}
	else
		return false;
}

bool TerpstraSysExApplication::redo()
{
	if (undoManager.redo())
	{
		// setHasChangesToSave(true);
		// ((MainContentComponent*)(mainWindow->getContentComponent()))->refreshAllFields();
		return true;
	}
	else
		return false;
}

// LumatoneColourModel* TerpstraSysExApplication::getColourModel()
// {
// 	return &colourModel;
// }

bool TerpstraSysExApplication::toggleDeveloperMode()
{
	state.setDeveloperMode(!state.getInDeveloperMode());
	return state.getInDeveloperMode();
	// bool newMode = !propertiesFile->getBoolValue("DeveloperMode");
	// propertiesFile->setValue("DeveloperMode", newMode);
	// return ((MainContentComponent*)(mainWindow->getContentComponent()))->state.setDeveloperMode(newMode);
}

// void TerpstraSysExApplication::state.setEditMode(EditorMode editMode)
// {
// 	state.setEditMode(editMode);
//     // lumatoneController->setSysExSendingMode(editMode);
// }

// bool TerpstraSysExApplication::generalOptionsDialog()
// {
// 	GeneralOptionsDlg* optionsWindow = new GeneralOptionsDlg();
// 	optionsWindow->setLookAndFeel(&lookAndFeel);

// 	DialogWindow::LaunchOptions launchOptions;
// 	launchOptions.content.setOwned(optionsWindow);
// 	launchOptions.content->setSize(480, 240);

// 	launchOptions.dialogTitle = "General options";
// 	launchOptions.dialogBackgroundColour = lookAndFeel.findColour(juce::ResizableWindow::backgroundColourId);
// 	launchOptions.escapeKeyTriggersCloseButton = true;
// 	launchOptions.useNativeTitleBar = false;
// 	launchOptions.resizable = true;

// 	DialogWindow* dw = launchOptions.launchAsync();
// 	dw->centreWithSize(480, 240);

// 	return true;
// }

// bool TerpstraSysExApplication::noteOnOffVelocityCurveDialog()
// {
// 	NoteOnOffVelocityCurveDialog* velocityCurveWindow = new NoteOnOffVelocityCurveDialog();
// 	velocityCurveWindow->setLookAndFeel(&lookAndFeel);

// 	int dlgWidth = propertiesFile->getIntValue("VelocityCurveWindowWidth", 648);
// 	int dlgHeight = propertiesFile->getIntValue("VelocityCurveWindowHeight", 424);

// 	DialogWindow::LaunchOptions launchOptions;
// 	launchOptions.content.setOwned(velocityCurveWindow);
// 	launchOptions.content->setSize(dlgWidth, dlgHeight);

// 	launchOptions.dialogTitle = "Note on/off velocity curve";
// 	launchOptions.dialogBackgroundColour = lookAndFeel.findColour(ResizableWindow::backgroundColourId);
// 	launchOptions.escapeKeyTriggersCloseButton = true;
// 	launchOptions.useNativeTitleBar = false;
// 	launchOptions.resizable = true;

// 	DialogWindow* dw = launchOptions.launchAsync();
// 	dw->centreWithSize(dlgWidth, dlgHeight);

// 	return true;
// }

// bool TerpstraSysExApplication::faderVelocityCurveDialog()
// {
// 	VelocityCurveDlgBase* velocityCurveWindow = new VelocityCurveDlgBase(LumatoneConfigTable::TableType::fader);
// 	velocityCurveWindow->setLookAndFeel(&lookAndFeel);

// 	int dlgWidth = propertiesFile->getIntValue("FaderVelocityCurveWindowWidth", 648);
// 	int dlgHeight = propertiesFile->getIntValue("FaderVelocityCurveWindowHeight", 424);

// 	DialogWindow::LaunchOptions launchOptions;
// 	launchOptions.content.setOwned(velocityCurveWindow);
// 	launchOptions.content->setSize(dlgWidth, dlgHeight);

// 	launchOptions.dialogTitle = "Fader velocity curve";
// 	launchOptions.dialogBackgroundColour = lookAndFeel.findColour(ResizableWindow::backgroundColourId);
// 	launchOptions.escapeKeyTriggersCloseButton = true;
// 	launchOptions.useNativeTitleBar = false;
// 	launchOptions.resizable = true;

// 	DialogWindow* dw = launchOptions.launchAsync();
// 	dw->centreWithSize(dlgWidth, dlgHeight);

// 	return true;
// }

// bool TerpstraSysExApplication::aftertouchVelocityCurveDialog()
// {
// 	VelocityCurveDlgBase* velocityCurveWindow = new VelocityCurveDlgBase(LumatoneConfigTable::TableType::afterTouch);
// 	velocityCurveWindow->setLookAndFeel(&lookAndFeel);

// 	int dlgWidth = propertiesFile->getIntValue("AftertouchVelocityCurveWindowWidth", 768);
// 	int dlgHeight = propertiesFile->getIntValue("AftertouchVelocityCurveWindowHeight", 424);

// 	DialogWindow::LaunchOptions launchOptions;
// 	launchOptions.content.setOwned(velocityCurveWindow);
// 	launchOptions.content->setSize(dlgWidth, dlgHeight);

// 	launchOptions.dialogTitle = "Aftertouch parameters";
// 	launchOptions.dialogBackgroundColour = lookAndFeel.findColour(ResizableWindow::backgroundColourId);
// 	launchOptions.escapeKeyTriggersCloseButton = true;
// 	launchOptions.useNativeTitleBar = false;
// 	launchOptions.resizable = true;

// 	DialogWindow* dw = launchOptions.launchAsync();
// 	dw->centreWithSize(dlgWidth, dlgHeight);

// 	return true;
// }


void TerpstraSysExApplication::requestConfigurationFromDevice()
{
	// if editing operations were done that have not been saved, give the possibility to save them
	if (state.getHasChangesToSave())
	{
		AlertWindow::showYesNoCancelBox(
			AlertWindow::AlertIconType::QuestionIcon,
			"Request configuration from device",
			"Lumatone's layout will now be imported. This will overwrite your unsaved changes. Do you want to save them first?",
			"Save to file", "Import anyway", "Cancel import", nullptr,
			ModalCallbackFunction::create([&](int retc)
			{
				if (retc == 0)
				{
					// "Cancel". Do not receive config, go offline
					DBG("Layout import cancelled");
                    state.setEditMode(EditorMode::OFFLINE);
					return;
				}
				else if (retc == 1)
				{
					// "Yes". Try to save. Cancel if unsuccessful
					saveSysExMapping([this](bool success)
					{
						if (success)
							this->requestConfigurationFromDevice();
						else
							DBG("Cancelled layout import");
					});
				}
				else
				{
					// retc == 2: "No" -> no saving, overwrite
					DBG("Overwriting current edits");
					// setHasChangesToSave(false);
					requestConfigurationFromDevice();
				}
			})
		);

		return;
	}

	resetSysExMapping();

	// Request MIDI channel, MIDI note, colour and key type config for all keys
	state.getLumatoneController()->sendGetCompleteMappingRequest();

	// General options
	state.getLumatoneController()->requestPresetFlags();
	state.getLumatoneController()->requestExpressionPedalSensitivity();

	// Velocity curve config
	state.getLumatoneController()->sendVelocityIntervalConfigRequest();
	state.getLumatoneController()->sendVelocityConfigRequest();
	state.getLumatoneController()->sendFaderConfigRequest();
	state.getLumatoneController()->sendAftertouchConfigRequest();
}

void TerpstraSysExApplication::updateMainTitle()
{
	String windowTitle("Lumatone Editor");

	if (!state.getCurrentFile().getFileName().isEmpty())
		windowTitle << " - " << state.getCurrentFile().getFileName();
	if (state.getHasChangesToSave())
		windowTitle << "*";
	mainWindow->setName(windowTitle);
}

// void TerpstraSysExApplication::setHasChangesToSave(bool value)
// {
	// if (value != hasCh)
	// {
		// hasChangesToSave = value;
		// updateMainTitle();
	// }
// }
//
//https://forum.juce.com/t/closing-dialog-windows-on-shutdown/27326/6
void TerpstraSysExApplication::setOpenDialogWindow(DialogWindow* dialogWindowIn)
{
    dialogWindow.reset(dialogWindowIn);

	// attach callback to window to release std::unique_ptr when the window is closed
	ModalComponentManager::getInstance()->attachCallback(dialogWindow.get(), ModalCallbackFunction::create([&](int r)
	{
        dialogWindow.release();
	}));
}

bool TerpstraSysExApplication::aboutTerpstraSysEx()
{
	String m;

	m << "Lumatone Editor" << newLine
		<< "Version " << getApplicationVersion() << newLine
		<< newLine
		<< "@ Hans Straub 2014 - 2021," << newLine
		<< "& Vincenzo Sicurella 2020 - 2022" << newLine
		<< newLine
		<< "Based on the program 'TerpstraSysEx' @ Dylan Horvath 2007" << newLine
		<< newLine
		<< "For help on using this program, or any questions relating to the Lumatone keyboard, go to:" << newLine
		<< newLine
		<< "https://www.lumatone.io/" << newLine
		<< newLine
		<< "Built " << Time::getCompilationDate().toString(true, true, false, true)
		<< " with " << SystemStats::getOperatingSystemName() << newLine
		<< "on " << SystemStats::getCpuModel() << newLine
		<< SystemStats::getJUCEVersion();

	DialogWindow::LaunchOptions options;
	auto textDisplay = new TextEditor();
	//textDisplay->setLookAndFeel(&lookAndFeel);
	state.getEditorLookAndFeel().setupTextEditor(*textDisplay);
	textDisplay->setMultiLine(true, true);
	textDisplay->setText(m, dontSendNotification);
	textDisplay->setFont(state.getAppFonts().getFont(LumatoneEditorFont::FranklinGothic));
	textDisplay->setReadOnly(true);
	textDisplay->setCaretVisible(false);
	options.content.setOwned(textDisplay);

	juce::Rectangle<int> area(0, 0, 400, 200);
	options.content->setSize(area.getWidth(), area.getHeight());

	//resizeLabelWithHeight(label, roundToInt(area.getHeight() * 0.24f));

	options.dialogTitle = "About Lumatone Editor";
	options.dialogBackgroundColour = state.getEditorLookAndFeel().findColour(LumatoneEditorColourIDs::DarkBackground);

	options.escapeKeyTriggersCloseButton = true;
	options.useNativeTitleBar = false;
	options.resizable = false;


	auto dw = options.launchAsync();
	//dw->setLookAndFeel(&lookAndFeel);
	dw->centreWithSize(400, 260);

	setOpenDialogWindow(dw);

	return true;
}

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION(TerpstraSysExApplication)
